lib/convallaria_web/router.ex
defmodule ConvallariaWeb.Router do
  use ConvallariaWeb, :router

  # 游客
  pipeline :tourist_user do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {ConvallariaWeb.LayoutView, :tourist_user}
  end

  # 注册登录用户
  pipeline :authenticated_user do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {ConvallariaWeb.LayoutView, :authenticated_user}
    plug ConvallariaWeb.Plugs.AuthenticatedUser
  end

  # 超级管理员
  pipeline :admin do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout, {ConvallariaWeb.LayoutView, :admin}
    plug ConvallariaWeb.Plugs.AdminUser
  end

  # 游客
  pipeline :tourist_api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  # 注册登录用户
  pipeline :authenticated_api do
    plug :accepts, ["json"]
    plug ConvallariaWeb.Plugs.AuthenticatedApi
  end

  scope "/", ConvallariaWeb do
    pipe_through :tourist_user # Use the default browser stack

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/contact", PageController, :contact

    get "/login", SessionController, :new
    post "/login", SessionController, :login, as: :login
    get "/logout", SessionController, :delete, as: :logout

    scope "/u" do
      pipe_through :authenticated_user # Use the default browser stack

      get "/", UserController, :dashboard
      resources "/users", UserController, singleton: true do
        get "/profile", UserController, :profile, as: :profile
      end

      resources "/products", ProductController
      resources "/devices", DeviceController
      resources "/follows", FollowController

    end

  end

  scope "/admin", ConvallariaWeb.Admin, as: :admin do
    pipe_through :admin

    get "/", PageController, :index
    resources "/users", UserController
    resources "/verify_codes", VerifyCodeController
    resources "/products", ProductController
    resources "/devices", DeviceController
    resources "/follows", FollowController

    resources "/account_avatars", AccountAvatarController

    scope "/" do
      get "/visual_iot", VisualController, :visual_iot

    end

    scope "/setting" do
      get "/account", SettingController, :account
      get "/password", SettingController, :password
      get "/profile", SettingController, :profile
      get "/reward", SettingController, :reward
      put "/change", SettingController, :change
    end

  end

  scope "/api", ConvallariaWeb.Api, as: :api do
    pipe_through :tourist_api

    post "/sign_up", RegistrationController, :register, as: :sign_up
    post "/sign_in", SessionController, :login, as: :sign_in
    post "/send_code", VerifyCodeController, :send_code, as: :send_code

    scope "/" do
      pipe_through :authenticated_api

      scope "/users" do
        get "/profile", UserController, :profile
      end
      resources "/devices", DeviceController, param: "device_key" do
        get "/status", DeviceController, :show, as: :status
      end

    end

  end



  # Other scopes may use custom stacks.
  # scope "/api", ConvallariaWeb do
  #   pipe_through :api
  # end
end

lib/convallaria_web/controllers/api/session_controller.ex
defmodule ConvallariaWeb.Api.SessionController do
  use ConvallariaWeb, :controller

  alias Convallaria.Accounts
  alias Convallaria.Accounts.User
  alias Convallaria.Password
  alias Convallaria.Token

  import Logger

  action_fallback ConvallariaWeb.Api.FallbackController

  #登录
  def login(conn, %{"mobile" => mobile, "password" => password}) do
    user = Accounts.get_user_by_mobile(mobile)
    if user do
      if Bcrypt.verify_pass(password, user.encrypted_password) && user.is_active do
        if user.is_active do
          last_login_at = user.last_login_at
          # 标注用户最后登录时间
          Accounts.update_user(user, %{last_login_at: DateTime.utc_now})
          render(conn, "login.json", token: token = Token.generate_token(user), user: user, last_login_at: last_login_at)
        else
          {:error, :user_unactived}
        end
      else
        {:error, :user_password}
      end
    else
      {:error, :user_exist}
    end

  end

  def login(conn, %{"mobile" => mobile, "password" => password}) do
    {:error, :no_matched_request}
  end

end

lib/convallaria_web/controllers/session_controller.ex
defmodule ConvallariaWeb.SessionController do
  use ConvallariaWeb, :controller

  alias Convallaria.Accounts
  alias Convallaria.Accounts.User
  alias Convallaria.Password
  alias Convallaria.Repo
  alias Convallaria.{
    Token,
    Mailer,
    Email
  }
  
  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  #登录
  def login(conn, %{"user" => user_params}) do
    user = Accounts.get_user_by_mobile(user_params["mobile"])
    
    if user do

      if Bcrypt.verify_pass(user_params["password"], user.encrypted_password) do
        if user.is_active do
          if user.is_admin do
            conn
            |> put_session(:current_user, user)
            |> put_session(:current_user_id, user.id)
            |> put_flash(:info, 'You are now signed in.')
            |> redirect(to: admin_page_path(conn, :index))
          else
            conn
            |> put_session(:current_user, user)
            |> put_session(:current_user_id, user.id)
            |> put_flash(:info, 'You are now signed in.')
            |> redirect(to: user_path(conn, :dashboard))
          end
        else
          conn
          |> put_flash(:error, '用户未激活')
          |> render("new.html", changeset: Accounts.change_user(%User{}) )
        end
      else
        conn
        |> put_flash(:error, 'Username or password are incorrect.')
        |> render("new.html", changeset: Accounts.change_user(%User{}) )
      end

    else
      conn
      |> put_flash(:error, "用户不存在")
      |> render("new.html", changeset: Accounts.change_user(%User{}) )
    end

  end

  #退出
  def delete(conn, _) do
    conn
    |> delete_session(:current_user)
    |> delete_session(:current_user_id)
    |> put_flash(:info, 'You have been logged out')
    |> redirect(to: session_path(conn, :new))

  end

  
end

lib/convallaria_web/views/session_view.ex
defmodule ConvallariaWeb.SessionView do
  use ConvallariaWeb, :view
end

lib/convallaria_web/templates/session/forgot_password.html.eex
<div class="card">
  <div class="card-header">忘记了密码?</div>
  <div class="card-body">
    <form class="new_user" id="new_user" action="/forgot_password_email" accept-charset="UTF-8" method="post">
      <input type="hidden" name="_method" value="post" />
      <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>" />
      <div class="form-group">
        <input type="email" class="form-control input-lg" placeholder="Email" name="user[email]" id="user_email">
        <p class="form-text text-muted">此功能将会发送一个找回密码的特别链接到你的邮箱，通过改链接可以进入重置密码的页面。</p>
      </div>
      <div class="form-actions">
        <input type="submit" name="commit" value="找回密码" class="btn btn-primary">
      </div>
    </form>
  </div>
</div>

lib/convallaria_web/templates/session/invalid_token.html.eex
<h1>Invalid token</h1>

lib/convallaria_web/templates/session/new.html.eex
<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card-group">
      <div class="card p-4">

      <%= form_for @changeset, login_path(@conn, :login), fn f -> %>
        <%= if @changeset.action do %>
          <div class="alert alert-danger">
            <p>Oops, something went wrong! Please check the errors below.</p>
          </div>
        <% end %>

        <div class="form-group">
          <label for="user_mobile" class="control-label">Mobile</label>
          <%= text_input f, :mobile, class: "form-control" %>
          <%= error_tag f, :mobile %>
        </div>

        <div class="form-group">
          <%= label f, :password, class: "control-label" %>
          <%= password_input f, :password, class: "form-control" %>
          <%= error_tag f, :password %>
        </div>

        <div class="row">
          <div class="col-6">
            <%= submit "Submit", class: "btn btn-primary" %>
          </div>
          <div class="col-3 text-right">
            <a class="btn btn-link px-0" type="button" href="/resend_verify_email">resend active email?</a>            
          </div>
          <div class="col-3 text-right">
            <a class="btn btn-link px-0" type="button" href="/forgot_password">Forgot password?</a>            
          </div>
        </div>
      <% end %>
      </div>
      <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
        <div class="card-body text-center">
          <div>
            <h2>Sign up</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <a class="btn btn-primary active mt-3" type="button" href="/join">Register Now!</a>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

lib/convallaria_web/templates/session/resend_verify_email.html.eex
<div class="card">
  <div class="card-header">重新发送激活邮件?</div>
  <div class="card-body">
    <form class="new_user" id="new_user" action="/resend_verify_email" accept-charset="UTF-8" method="post">
      <input type="hidden" name="_method" value="post" />
      <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>" />
      <div class="form-group">
        <input type="email" class="form-control input-lg" placeholder="Email" name="user[email]" id="user_email">
        <p class="form-text text-muted">此功能会发送激活连接到您的邮箱 点击连接激活账户</p>
      </div>
      <div class="form-actions">
        <input type="submit" name="commit" value="发送激活邮件" class="btn btn-primary">
      </div>
    </form>
  </div>
</div>

lib/convallaria_web/templates/session/reset_password.html.eex
<div class="card">
  <div class="card-header">修改密码</div>
  <div class="card-body">
    <%= form_for @changeset, session_path(@conn, :update_password), fn f -> %>
      <input type="hidden" value="<%= @token %>" name="user[reset_password_token]" id="user_reset_password_token">
      <div class="form-group">
        <%= password_input f, :password, class: "form-control", required: true, placeholder: "密码" %>
        <%= error_tag f, :password %>
      </div>
      <div class="form-group">
        <%= password_input f, :password_confirmation, class: "form-control", required: true, placeholder: "确认密码" %>
        <%= error_tag f, :password_confirmation %>
      </div>
      <div class="form-actions">
        <%= submit "修改密码", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>